version: '3.7'

services:
  lume-test:
    image: tidair/lume-impact-live-demo:latest
    container_name: lume-test
    tty: true
    stdin_open: true
    volumes:
      - type: volume
        source: data-volume
        target: /output

  sftp-server:
    image: atmoz/sftp
    container_name: sftp-server
    volumes:
      - type: volume
        source: data-volume
        target: /home/test/lume
    ports:
      - target: 22
        published: 2222
        protocol: tcp
        mode: host
    command: test:test:::lume

volumes:
  data-volume:
    name: lume-data-volume
